module Game
  class Camera
    attr_reader window: Window
    def initialize: (Window) -> void
    def displayed_entities: -> Array[Entity]
    def grid: -> Grid
    def update: (Window) -> Window
  end
end