module Game
  class Player < Entity
    attr_reader room: Room | nil
    attr_reader blocked_camera: bool

    def intitialize: (Window) -> void
    def enter: (Room) -> Room
    def leave: -> nil
    def outside?: -> bool
    def room?: -> bool
    def move: (Symbol) -> void
  end
end