module Game
  class Window
    attr_reader rules : Rules
    attr_reader player : Player
    attr_reader entities : Array[Entity]
    attr_reader camera : Camera
    def initialize: -> void
    def update: -> void
    def draw: -> void
    def quad_tree: (Array[Entity], Grid | nil) -> QuadTree
    def entity_over_entity: (Entity, Grid | nil) -> Array[Entity]
    def allowed_next_move?: (Entity, Symbol) -> bool
  end
end